#pragma config(Sensor, in1,    angle,          sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightDrive,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftDrive,      sensorQuadEncoder)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port3,           angleYCable,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftShooter,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           divider,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           rightShooter,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightRear,     tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftRear,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void Drive(int fLeft, int rLeft, int fRight, int rRight)
{
	motor[leftFront] = fLeft;
	motor[leftRear] = rLeft;
	motor[rightFront] = fRight;
	motor[rightRear] = rRight;
	wait1Msec(20);
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	while (true)
	{
		if(SensorValue[angle] <= 400)
		{
			motor[angleYCable] = 30;
			wait1Msec(20);
		}
		else
		{
			motor[angleYCable] = 0;
			motor[leftShooter] = 127;
			motor[rightShooter] = 127;
			wait1Msec(20);
		}
	}
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
	while (true)
	{
		motor[leftFront] = vexRT[Ch3];
		motor[leftRear] = vexRT[Ch3];
		motor[rightFront] = vexRT[Ch2];
		motor[rightRear] = vexRT[Ch2];
		wait1Msec(10);

	if(vexRT[Btn6DXmtr2] == 1)
	{
		motor[leftShooter] = 127;
		wait1Msec(20);
	}

	else
	{
		motor[leftShooter] = 15;
	}

	if(vexRT[Btn6UXmtr2] == 1)
	{
		motor[rightShooter] = 127;
		wait1Msec(20);
	}

	else
	{
		motor[rightShooter] = 15;
		wait1Msec(20);
	}

	if(vexRT[Btn8RXmtr2] == 1)
	{
		motor[divider] = 127;
		wait1Msec(20);
	}

	else if(vexRT[Btn8DXmtr2] == 1)
	{
		motor[divider] = -127;
		wait1Msec(20);
	}
	if(vexRT[Btn8LXmtr2] == 1)
	{
		motor[intake] = -127;
		wait1Msec(20);
	}
	else if(vexRT[Btn8UXmtr2] == 1)
	{
		motor[intake] = 127;
		wait1Msec(20);
	}
	if(vexRT[Btn7UXmtr2] == 1 && SensorValue[angle] >= 400)
	{
		motor[angleYCable] = 0;
	}
	else
	{
		motor[angleYCable] = vexRT[Ch2Xmtr2];
	}


	}
}


    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
