#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftFront,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftRear,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightFront,     sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  rightRear,      sensorQuadEncoder)
#pragma config(Motor,  port1,           shooterL,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftRear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightRear,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           shooterR,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           angle,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		{
			motor[intake] = 127;
			motor[rightFront] = vexRT[Ch2];
			motor[rightRear] = vexRT[Ch2];
			motor[leftFront] = vexRT[Ch3];
			motor[leftRear] = vexRT[Ch3];
			wait1Msec(20);
		}

		if(vexRT[Btn6U] == 1)
		{
			{
				motor[shooterL] = 127;
				motor[shooterR] = 127;
				wait1Msec(20);
			}
		}
		else
		{
			{
				motor[shooterL] = 5;
				motor[shooterR] = 5;
				wait1Msec(20);
			}
		}
		if(vexRT[Btn5U] == 1)
		{
			{
				motor[angle] = 40;
			}
		}
		else if(vexRT[Btn5D] == 1)
		{
			{
				motor[angle] = -15;
				wait1Msec(20);
			}
		}
		else
		{
			{
				motor[angle] = 15;
				wait1Msec(20);
			}
		}
	}
}
