#pragma config(Motor,  port2,           leftRearB,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightRearA,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightRearB,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftRearA,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[leftRearA] = vexRT[Ch3];
		motor[leftRearB] = vexRT[Ch3];
		motor[leftFront] = vexRT[Ch3];
		motor[rightRearA] = vexRT[Ch2];
		motor[rightRearB] = vexRT[Ch2];
		motor[rightFront] = vexRT[Ch2];
		wait1Msec(20);
	}



}
